/**
 * Stable, machine-readable error codes. Spec §3.6 and Appendix B.
 * `code` is an enum the dashboard switches on; `message` is safe to show a
 * receptionist verbatim.
 */
export const ErrorCode = {
  // Booking conflicts -- raised by the database exclusion constraints (SQLSTATE 23P01)
  THERAPIST_ALREADY_BOOKED: 'THERAPIST_ALREADY_BOOKED',
  ROOM_ALREADY_BOOKED: 'ROOM_ALREADY_BOOKED',
  GUEST_ALREADY_BOOKED: 'GUEST_ALREADY_BOOKED',
  SLOT_CONFLICT: 'SLOT_CONFLICT',

  // Reservation lifecycle
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  RESERVATION_NOT_SCHEDULED: 'RESERVATION_NOT_SCHEDULED',
  RESERVATION_NOT_IN_PROGRESS: 'RESERVATION_NOT_IN_PROGRESS',
  ILLEGAL_STATUS_TRANSITION: 'ILLEGAL_STATUS_TRANSITION',

  // Money
  BASE_PAYMENT_MISMATCH: 'BASE_PAYMENT_MISMATCH',
  BASE_PAYMENT_OUTSTANDING: 'BASE_PAYMENT_OUTSTANDING',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  TIP_METHOD_REQUIRED: 'TIP_METHOD_REQUIRED',
  TIP_METHOD_NOT_ALLOWED: 'TIP_METHOD_NOT_ALLOWED',
  TIP_EXCEEDS_SANITY_LIMIT: 'TIP_EXCEEDS_SANITY_LIMIT',
  TIP_ALREADY_REVERSED: 'TIP_ALREADY_REVERSED',
  TIP_ALREADY_PAID_OUT: 'TIP_ALREADY_PAID_OUT',
  PAYOUT_NOT_POSITIVE: 'PAYOUT_NOT_POSITIVE',
  ARRIVAL_TIME_IMPLAUSIBLE: 'ARRIVAL_TIME_IMPLAUSIBLE',
  COMPLETION_BEFORE_ARRIVAL: 'COMPLETION_BEFORE_ARRIVAL',

  // Idempotency
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  REQUEST_IN_PROGRESS: 'REQUEST_IN_PROGRESS',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  PASSWORD_TOO_COMMON: 'PASSWORD_TOO_COMMON',

  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiErrorBody {
  error: {
    code: ErrorCode | string;
    message: string;
    details?: Record<string, unknown>;
    requestId?: string;
  };
}
